version: '3.4'

services:

  SqlServerDb:
        container_name: SqlServerContainer
        ports:
            - "8000:1433"
        environment:
            - ACCEPT_EULA=Y 
            - SA_PASSWORD=Docker1234
        networks:         
            - myAppNetwork 
  
  hospital.services.authapi:
     container_name: authapicontainer
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DbConnection=Server=SqlServerDb;Database=HMSDev;User Id=sa;Password=Docker1234"
     depends_on:
      - SqlServerDb
     ports:
      - "8001:80"
  
  hospital.services.clinicapi:
    container_name: clinicapicontainer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DbConnection=Server=SqlServerDb;Database=HMSDev;User Id=sa;Password=Docker1234"
    depends_on:
      - SqlServerDb
    ports:
      - "8002:80"
  
  hospital.services.bedapi:
    container_name: bedapicontainer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DbConnection=Server=SqlServerDb;Database=HMSDev;User Id=sa;Password=Docker1234"
    depends_on:
      - SqlServerDb
    ports:
      - "8003:80"


  # hospital.services.authapi:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #   ports:
  #     - "80"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro